---
title: "**Publications**"
output: 
  html_document:
    toc: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>
<br>
"corresponding
<br>
<br>

### For stats, you may want to look at [Google Scholar](https://scholar.google.de/citations?user=u21upHAAAAAJ&hl=en)  

<br>
<br>

### 2023
<br>

**Crean EE, M Bilstein-Schloemer M**, T Maekawa T, P Schulze-Lefert P, **Saur IML"**. A dominant-negative avirulence effector of the barley powdery mildew fungus provides mechanistic insight to barley MLA immune receptor activation. **J Exp Botany** doi: 10.1093/jxb/erad285

<br>

**Shi W**, Stolze SC, Nakagami H, Misas Villamil JC, **Saur IML**, Doehlemann G". Combination of in-vivo proximity labeling and co-immunoprecipitation identifies the host target network of a tumor-inducing effector in the fungal maize pathogen Ustilago maydis. **J Exp Botany** doi: 10.1093/jxb/erad188.

<br>

Yu G, Matny O, Gourdoupis S, Rayapuram N, Aljedaani FR, Wang YL, Nürnberger T, Johnson R, **Crean EE, Saur IML**, Gardener C, Yue Y, Kangara N, Steuernagel B, Hayta S, Smedley M, Harwood W, Patpour M, Wu S, Poland J, Jones JDG, Reuber TL, Ronen M, Sharon A, Rouse MN, Xu S, Holušová K, Bartoš J, Molnár I, Karafiátová M, Hirt H, Blilou I, Jaremko Ł, Doležel J, Steffenson BJ", Wulff BBH". The wheat stem rust resistance gene Sr43 encodes an unusual protein kinase. **Nature Genetics** doi: 10.1038/s41588-023-01402-1


<br>

Wanke A, van Boerdonk S, Mahdi LK, Stephan Wawra S, Neidert M, Chandrasekar B, Saake P, **Saur IML**, Derbyshire P, Holton N, Menke FLH, Brands M, Pauly M, Acosta IF, Zipfel C, Zuccaro A". A GH81-type β-glucan-binding protein facilitates colonization by mutualistic fungi in barley. **bioRxiv** doi:10.1101/2023.04.12.536646

<br>
<br>

### 2022

<br>

Märkle H, **Saur IML**, Stam R". Evolution of resistance (R) gene specificity. **Essays in Biochemistry** doi:10.1042/EBC20210077

<br>

Ortiz D, Chen J, Outram MA, **Saur IML**, Upadhyaya NM, Mago R, Ericsson DJ, Cesari S, Chen C, Williams SJ", Dodds PN". The stem rust effector protein AvrSr50 escapes Sr50 recognition by a substitution in a single surface-exposed residue. **New Phytologist** doi:10.1111/nph.18011

<br>

**Saur IML"**, Lawson AW, Schulze-Lefert P". Buy one, get two. **Nature Plants** doi: 10.1038/s41477-022-01097-y

<br>
<br>


### 2021

<br>

**Saur IML"**, Hückelhoven R". **Humboldt-Review 2021**: Recognition and defence of plant-infecting fungal pathogens. **J Plant Physiology** doi:10.1016/j.jplph.2020.153324. 

<br>

**Saur IML**, Panstruga R, Schulze-Lefert P". NOD-like receptor-mediated plant immunity: from structure to cell death. **Nature Reviews Immunology** doi: 10.1038/s41577-020-00473-z

<br>

Bauer S, Yu D, Lawson AW, **Saur IML**, Frantzeskakis L, Kracher B, Logemann E, Chai J, Maekawa T, Schulze-Lefert P". The leucine-rich repeats in allelic barley MLA immune receptors define specificity towards sequence-unrelated powdery mildew avirulence effectors with a predicted common RNase-like fold. **PLoS Pathogens** doi: 10.1371/journal.ppat.1009223

<br>
<br>

### 2020

<br>

Mahdi LK, Huang M, Zhang X, Nakano RT, Kopp LB, **Saur IML**, Jacob F, Kovacova V, Lapin D, Parker JE, Murphy JM, Hofmann K, Schulze-Lefert P, Chai J, Maekawa T". Discovery of a Family of Mixed Lineage Kinase Domain-like Proteins in Plants and Their Role in Innate Immune Signaling. **Cell, Host & Microbe** doi: 10.1016/j.chom.2020.08.012. 

<br>
<br>

### 2019

<br>

**Saur IML"**, Bauer S, Lu X, Schulze-Lefert P". A cell death assay in barley and wheat protoplasts for identification and validation of matching pathogen AVR effector and plant NLR immune receptors. **Plant Methods** doi: 10.1186/s13007-019-0502-0. 

<br>

**Saur IML**, Bauer S, Kracher B, Lu X, Franzeskakis L, Müller MC, Sabelleck B, Kümmel F, Panstruga R, Maekawa T, Schulze-Lefert P". Multiple pairs of allelic MLA immune receptor-powdery mildew AVRA effectors argue for a direct recognition mechanism. **Elife** doi: 10.7554/eLife.44471

<br>

Maekawa T, Kracher B, **Saur IML**, Yoshikawa-Maekawa M, Kellner R, Pankin A, von Korff M, Schulze-Lefert P". Subfamily-Specific Specialization of RGH1/MLA Immune Receptors in Wild Barley. **Mol Plant Microbe Interact** doi: 10.1094/MPMI-07-18-0186-FI.

<br>
<br>

### 2018

<br>

Conlan B", Stoll T, Gorman JJ, **Saur IML**, Rathjen JP". Development of a Rapid in planta BioID System as a Probe for Plasma Membrane-Associated Immunity Proteins. **Front Plant Sci** doi: 10.3389/fpls.2018.01882

<br>
<br>

### 2017

<br>

Thynne E, **Saur IML**, Simbaqueba J, Ogilvie HA, Gonzalez-Cendales Y, Mead O, Taranto A, Catanzariti AM, McDonald MC, Schwessinger B, Jones DA", Rathjen JP", Solomon PS". Fungal phytopathogens encode functional homologues of plant rapid alkalinization factor (RALF) peptides.**Mol Plant Pathol** doi: 10.1111/mpp.12444.

<br>
<br>

### 2016

<br>

Lu X, Kracher B, **Saur IML**, Bauer S, Ellwood SR, Wise R, Yaeno T, Maekawa T, Schulze-Lefert P". Allelic barley MLA immune receptors recognize sequence-unrelated avirulence effectors of the powdery mildew pathogen. **PNAS USA** doi: 10.1073/pnas.

<br>

Pfeilmeier S, **Saur IML**, Rathjen JP, Zipfel C", Malone JG". High levels of cyclic-di-GMP in plant-associated Pseudomonas correlate with evasion of plant immunity. **Mol Plant Pathol** doi: 10.1111/mpp.12297

<br>

**Saur IML**, Kadota Y, Sklenar J, Holton NJ, Smakowska E, Belkhadir Y, Zipfel C", Rathjen JP". NbCSPR underlies age-dependent immune responses to bacterial cold shock protein in Nicotiana benthamiana. **PNAS USA** doi: 10.1073/pnas.1511847113

<br>
<br>

### 2015

<br>

**Saur IML**, Conlan BF, Rathjen JP". The N-terminal domain of the tomato immune protein Prf contains multiple homotypic and Pto kinase interaction sites. **J Biol Chem** doi:10.1074/jbc.M114.616532.

<br>

Ntoukakis V, **Saur IML**, Conlan B, Rathjen JP". The changing of the guard: the Pto/Prf receptor complex of tomato and pathogen recognition. **Curr Opin Plant Biol** doi: 10.1016/j.pbi.2014.04.002

<br>
<br>

### 2011

<br>

**Saur IML**, Oakes M, Djordjevic MA, Imin N". Crosstalk between the nodulation signaling pathway and the autoregulation of nodulation in Medicago truncatula. **New Phytologist** doi: 10.1111/j.1469-8137.2011.03738.

<br>
<br>
<br>


© Isabel Saur